#!/usr/bin/env python3

import argparse
try:
    from cStringIO import StringIO
except ImportError:
    from io import StringIO
from distutils.dir_util import copy_tree
import math
import os
import re
import subprocess
import sys
import tempfile

# from em import Interpreter
from gazebo_msgs.srv import DeleteModel
from gazebo_msgs.srv import DeleteModelRequest
from gazebo_msgs.srv import SpawnModel
from gazebo_msgs.srv import SpawnModelRequest
from rosgraph import ROS_MASTER_URI
from rospkg import RosPack
from rospy import ServiceProxy
from rospy import myargv as rospy_myargv
from rospy import wait_for_service


def spawn_model(model_name, model_xml,
    pose, ros_master_uri=None, robot_namespace=None, debug=True,
    service_name='/gazebo/spawn_sdf_model',
):
    x, y, yaw = pose
    INITIAL_HEIGHT = 0.5 # m

    if ros_master_uri:
        original_uri = os.environ[ROS_MASTER_URI]
        os.environ[ROS_MASTER_URI] = ros_master_uri
    wait_for_service(service_name)
    srv = ServiceProxy(service_name, SpawnModel)

    if debug:
        print(model_xml)

    req = SpawnModelRequest()
    req.model_name = model_name
    req.model_xml = model_xml
    req.robot_namespace = robot_namespace if robot_namespace else model_name
    req.initial_pose.position.x = x
    req.initial_pose.position.y = y
    req.initial_pose.position.z = INITIAL_HEIGHT
    req.initial_pose.orientation.x = 0.0
    req.initial_pose.orientation.y = 0.0
    req.initial_pose.orientation.z = math.sin(yaw / 2.0)
    req.initial_pose.orientation.w = math.cos(yaw / 2.0)
    req.reference_frame = ''

    resp = srv(req)

    if ros_master_uri:
        os.environ[ROS_MASTER_URI] = original_uri

    if resp.success:
        print(resp.status_message, '(%s)' % model_name)
        return 0
    else:
        print(resp.status_message, file=sys.stderr)
        return 1


def get_px4_dir():
    rp = RosPack()
    return rp.get_path('px4')


def seed_rootfs(rootfs):
    px4_dir = get_px4_dir()
    copy_tree(px4_dir, rootfs)


def run_px4(rc_script='etc/init.d-posix/rcS', px4_sim_model='iris', rootfs=None):
    """ Replacing run_px4.sh
    rc_script is the path to the rc_script to run
    px4_sim_model is the model
    if rootfs is set use that for the rootfs, otherwise run in a temporary directory.
    """
    if not rootfs:
        with tempfile.TemporaryDirectory() as tempdir:
            return run_px4(rc_script, px4_sim_model, tempdir)

    print("using rootfs ", rootfs)
    seed_rootfs(rootfs)

    cmd = ['px4', '%s/ROMFS/px4fmu_common' % rootfs, 
           '-s', rc_script,
           '-d']
    print("running px4 with command: ", cmd)
    subprocess_env = os.environ.copy()
    subprocess_env['PX4_SIM_MODEL'] = px4_sim_model
    subprocess.check_call(
        cmd,
        cwd=rootfs,
        env=subprocess_env)


def spawn_typhooon():
    with open('/home/osrf/diux/src/sitl_gazebo/models/typhoon_h480/typhoon_h480.sdf') as fh:
        model_xml = fh.read()
    spawn_model('typhoon_h480', model_xml, (0,0,0))


def spawn_iris():
    with open('/home/osrf/diux/src/sitl_gazebo/models/iris_fpv_cam/iris_fpv_cam.sdf') as fh:
        model_xml = fh.read()
    spawn_model('iris', model_xml, (0,0,0))


def spawn_plane():
    with open('/home/osrf/diux/src/sitl_gazebo/models/plane_cam/plane_cam.sdf') as fh:
        model_xml = fh.read()
    spawn_model('plane', model_xml, (0,0,0))


def main():
    SUPPORTED_DRONE_TYPES=['typhoon_h480', 'iris', 'plane']

    parser = argparse.ArgumentParser(description='Spawn a drone')
    parser.add_argument('drone_type', help="What type of drone", choices=SUPPORTED_DRONE_TYPES)

    myargv = rospy_myargv(argv=sys.argv)[1:]
    print("myargv", myargv)
    args = parser.parse_args(args=myargv)
    if args.drone_type == 'typhoon_h480':
        spawn_typhooon()
    elif args.drone_type == 'iris':
        spawn_iris()
    elif args.drone_type == 'plane':
        spawn_plane()
    run_px4('etc/init.d-posix/rcS', args.drone_type)

if __name__ == '__main__':
    main()